function(clang_format_display files)
    if(!${HAVE_CLANG_FORMAT})
        find_program(HAVE_CLANG_FORMAT clang-format)
        if(${HAVE_CLANG_FORMAT})
            foreach(input_file IN ${files})
                execute_process(${HAVE_CLANG_FORMAT} ${input_file})
            endforeach()
        elseif()
            message("Clang format not found")
        endif()
    endif()
endfunction()
